pilot.py
pilot/util/config.py

I forgot it. From previous realization

Removed an old forgotten thing. (and added several magics)

---

pilot.py

Forgot to delete earlier implementation

Removed an old thing

---

pilot/api/data.py
pilot/util/copytools.py

Added xrdcp copytool and refactored rucio copytool.
I'm not sure if the location (pilot/util/copytool.py) is good.
Calls to the copytools are still missing. AGIS should be queried in api/data.py to decide what copytool should be used. I will do this in a separate branch when you think this implementation is ok.

Use xrdcp for root

---

.gitignore
pilot/common/__init__.py
pilot/common/exception.py

Feature exception model

---

.flake8
.travis.yml
job.py
job_description_fixer.py
jobdescription.py
pilot.py

Created and tested a job description class, that can provide views on properties in several ways.
Uses the same way, minipilot accesses the properties and can be easily integrated into any pilots related software.
Not documented yet.

Job description class

---

doc/components/control/payloads/eventservice.rst
doc/components/control/payloads/generic.rst
doc/components/control/payloads/index.rst
pilot.py
pilot/test/test_exception.py
pilot/user/atlas/common.py
pilot/user/atlas/container.py

* Refactored job report functions and added more of them
* Added middleware from container function
* Updated documentation (payloads directory added)

Job report functions and documentation

---

pilot/control/payload.py

Jobreport parsing feature from Doug

---

.flake8
pilot.py
pilot/control/data.py
pilot/control/job.py
pilot/control/payload.py

* Now extracting exit code and message from job report and using it to identify failed payload
* Added flake8 error codes to ignore list: E262,E265,E266,N804

Job report exit code handling

---

pilot.py
pilot/.config/flake8

Previously only file .flake8 existed which should be for Windows systems

Added .config/flake8 (for linux systems)

---

pilot/copytool/lsm.py

Hi, I've created a first version of LSM fetch. The structure was copied from my GFAL2 module.
Will be happy to hear a feedback during testing.

Added LSM copy tool

---

pilot.py
pilot/user/atlas/container.py
pilot/user/atlas/setup.py
pilot/util/container.py
pilot/util/harvester.py
pilot/util/information.py
pilot/util/parameters.py
pilot/util/workernode.py

* Clean-up of deprecated code (in favour of infosys component)
* ALRB containerisation now working properly
* Removed shell=true from Popen in execute(), using bash instead of sh
* Automatic Harvester detection (setting of Harvester mode)

General improvements

---

pilot/info/dataloader.py
pilot/util/timer.py

- Implemented Timer related classes to time-out the execution of a fu…
…nction, in particular by using decorator style.
Supports Process-Based approach (TimedProcess) for a production usage and restricted Thread-Based implementation (TimedThread, Windows compatible)
- Upgraded DataLoader to consider time-out limit for reading plain files (CVMFS issue)

timeout control (Timer class), DataLoader upgrade

---

pilot/test/test_jobreport_parser.py
pilot/user/atlas/common.py

Removed some variables in the final report, added a test

Job report parsing

---

pilot/copytool/rucio.py

A stage-out feature. Please check that copy_out function declaration conforms with other requirements.

RUCIO stage-out

---

pilot/util/container.py
pilot/util/default.cfg
pilot/util/harvester.py
pilot/workflow/generic_hpc.py

Hpc workflow

---

pilot/common/errorcodes.py
pilot/common/exception.py

copy errorcodes from pilot1. 
updated the google doc https://docs.google.com/document/d/1MzLDB6s_RA4NqrxXGq645nE0Tx9iGR9kRx2QwWbdEuQ/edit?usp=sharing

copy es errorcodes from pilot1

---

pilot/api/data.py

**Updates:**
- resolve_replicas() logic updated to consider protocol priories exposed by Rucio
- resolve_replica fix to consider first direct access compatible protocols
**Notes:**
Direct access look up logic: if a PQ has several DDMs associated and direct access mode requested for input, then direct read will be used only if direct access compatible replica is stored at 1st DDMEndpoint, otherwise copy to scratch will be applied. Is it OK in terms of expected behavior?
Paul, can you please run test jobs for direct_access checks. thanks. I have not tested with real jobs this part.

resolve_replicas and direct access updates

---

pilot/api/data.py

Data API updated to be used by third-party applications:
-  simplify initialization
-  fix/ignore direct access settings by default if `infosys` instance is not initialized
**Examples**
1. An example of data API usage without `infosys` initialization
```python
from pilot.api import data
from pilot.info import FileSpec
client = data.StageInClient()
files = [{'scope':'mc16_13TeV', 'lfn': 'EVNT.11320990._003958.pool.root.1', 'destination': '/ccs/home/doleynik/test/', 'ddmendpoint':'CERN-PROD_DATADISK'}]
xfiles = [FileSpec(type='input', **f) for f in files]
r = client.transfer(xfiles)
```
2. An example of data API usage with explicitly initialized `infosys` instance
```python
from pilot.api import data
from pilot.info import InfoService, FileSpec, infosys
infoservice = InfoService() …
```

Data API updates

---

.travis.yml

freeze flake8 version

---

pilot/user/atlas/container.py

properly quote command to be passed as input for the wrapper
Paul, can you please test.
I emulated it locally and it looks like it should work as expected

fix passing command to singularity wrapper

---

pilot/copytool/rucio.py

Rucio mover updates: introduce `ignore_errors` input argument to skip errors with transfer files (for stage-in and stage-out).
and example of usage:
```python
client = data.StageInClient()
r = client.transfer(xfiles, ignore_errors=True)
```

Rucio mover update (ignore_errors)

---

pilot/control/data.py

revert accidentally overwritten change

---

pilot/info/queuedata.py

Expose `use_pcache` field in `QueueData`

Expose use_pcache in QueueData

---

pilot/control/job.py
pilot/util/harvester.py

made change to add routines to the harvester.py file. for running generic workflows

changes to allow generic workflows from Harvester on an HPC Edge node

---

pilot/eventservice/esprocess/esmessage.py
pilot/eventservice/esprocess/esprocess.py

use different socketname for yampl, to avoid yampl cross talking.

fix yampl cross talking

---

pilot/util/constants.py
pilot/util/monitoring.py

Added a protection for a problem with reading/parsing prmon output. Discovered by D. Cameron.

2.1.21 (17)

---

MANIFEST.IN

Added MANIFEST file. This file will include the files (python code is included by default) that will be present in the distributed package and needed for the pypi release.

added MANIFEST file

---

pilot/api/data.py
pilot/test/test_utils.py

Keep caught errors consistently as Exception objects and set stage in/out codes correctly

fix stage in/out code and propagate first error message

---

pilot/api/data.py

fix `resolve_replica` logic (return `None` rather than throw exception in case of missed replica)

resolve_replica fix

---

pilot/control/data.py
pilot/info/queuedata.py

follow PanDA orders for output destination only for `unified` PQs (PQ.type='unified')

Stage out fix for analy prod unification 

---

pilot/copytool/rucio.py

Needs testing. There is a method called copy_in_bulk. This acts as dead code for the time being, but pls test it and if works, use that as default.

Bulks in rucio copytool

---

pilot/copytool/rucio.py

Just adding pcaches option. Unit test not finished yet.

Next - pcaches

---

pilot/user/atlas/setup.py

add bits in setup command when running with Harvester on the edge

changes for Harvester

---

pilot/control/data.py
pilot/control/job.py
pilot/util/processes.py

Hi @PalNilsson : as follow up to our email discussion, this propagates the `cleanup` argument to parts where event service folders and outputs are being removed.

propagate args to cleanup code

---

pilot/eventservice/workexecutor/plugins/raythenaexecutor.py
pilot/eventservice/workexecutor/workexecutor.py

Plugin for event service with raythena. Similar to genericexecutor, but stage-out and cleanup is removed and output files are not zipper but rather reported back individually.

add raythenaexecutor plugin

---

pilot/eventservice/workexecutor/plugins/baseexecutor.py

Paul please review the code. While I tested it for raythena, i did not test it with a  traditional event job. 
The logic seems sound so I do not expect a problem.

add new default for raythena

---

pilot/user/atlas/container.py

just turned off verification caching for payload proxies

does not use cache in verification of payload proxy

---

pilot/copytool/gs.py

Hi Paul,
I modified the plugin gs.py, and tested it successfully. Please help integrate into the master branch.
Thanks,
Shuwei

Changed gs.py for GCS buckets with automatic bucket name extraction
