PanDAWMS/pilot2

- pilot/util/config.py
To make error reporting more readable and adequate.
The issue #15 showed that this error reporting is necessary for understanding the issues of this kind (see patch #16 for more information).
> Added expected convenient error reporting in the config magics.

- pilot/control/job.py
- pilot/util/disk.py
- pilot/util/https.py
- pilot/util/workernode.py
Small fixes required to run pilot in dev/test environment:
- https: avoid uncontrolled exception if user has no VOMS proxy initialized
- workernode.get_node_name(): failover to socket.gethostname for non UNIX platform
- job.validate(): consider creating symlink for the pilotlog.txt as non fatal error
- disk.disk_usage(): add stub implementation for non UNIX platforms
> Small fixes

- pilot/info/basedata.py
- pilot/info/configinfo.py
- pilot/info/queuedata.py
updates for pilot.info data containers:
- added final validation handler `clean` to check/clean-up required fields at the step when all custom field-specific validation passed
- use field value defined in class level as a default
QueueData updates: 
- added new fields (corecount, pledgedcpu, zip_time_gap, es_stageout_gap)
**Notes (TO BE CLARIFIED):**
I introduced new field `es_stageout_gap` - which is considered as `zip_time_gap` for ES workflow, if in general `zip_time_gap` is only applied/relevant to ES, than this new field looks redundant, otherwise can we invent proper names for it, like `stageout_gap` for normal jobs and `es_stageout_gap` for ES?
> pilot.info queuedata updates

- pilot/control/data.py
- pilot/control/job.py
- pilot/control/payload.py
- pilot/control/payloads/eventservice.py
- pilot/control/payloads/generic.py
- pilot/eventservice/eventrange.py
- pilot/info/__init__.py
- pilot/info/basedata.py
- pilot/info/jobdata.py
- pilot/info/jobinfo.py
- pilot/info/queuedata.py
- pilot/user/atlas/common.py
- pilot/user/atlas/container.py
- pilot/user/atlas/setup.py
- pilot/util/information.py
Initial Job class implementation (JobData) based on `pilot.info` data container:
- added few object fields as an example (jobid, taskid, jobparams, transformation, corecount, platform)
- kept backward compatible dict-based behavior  (to be removed once migrated)
- updated control/job workflow to expose new Job object
The Job class will be upgraded later with full list of functionality.
Updated somewhere logic to consider new `JobData` structure:
- migrated: `job['PandaID']` -> `job.jobid` 
- migrated: `job['working_dir']` -> `job.workdir`
- migrated: `job['infosys']` -> `job.infosys`
- replaced  wrapper `is_user_analysis_job()` -> job.is_analysis()
plus other updates for `QueueData` and `pilot.info`
regards,
Alexey
> Job class implementation based on pilot.info

- doc/components/index.rst
- doc/components/resource/generic.rst
- doc/components/resource/index.rst
- doc/components/resource/titan.rst
- pilot.py
- pilot/resource/__init__.py
- pilot/resource/generic.py
- pilot/resource/titan.py
- pilot/user/atlas/common.py
- pilot/workflow/generic.py
- pilot/workflow/generic_hpc.py
* Added generic HPC workflow and resource modules. Pilot option --hpc-resource _resource_ (and corresponding pilot 2 wrapper option -x  _resource_) can be used to specify the resource (e.g. titan). The HPC workflow can be selected with the existing pilot option -w generic_hpc. This will select the corresponding pilot.workflow.generic_hpc module which currently has some preliminary code that pulls in some of the functions (as examples) that were migrated from the HPC Pilot developed by D. Oleynik. See the code for more info. The resource specific code is available in the pilot.resource directory (currently some initial code exists for _titan_ and _generic_, specifically the get_setup() function).Note: this workflow is separate from the standard generic pilot workflow, which means that it …
> HPC workflow

- pilot/control/data.py
- pilot/info/basedata.py
- pilot/info/filespec.py
- pilot/info/jobdata.py
pilot info updates (FileSpec):
- base implementation of FileSpec class (encapsulates File related properties like lfn, dataset, checksum, guid, etc for input, output and log files, support of data validation)
- added corresponding fields to Job class to host the list of FileSpec entries (job.indata, job.outdata, job.logdata) for input/output/log files
- as an example, replace old job.{logfile, scopelog, logguid} occurrence with job.logdata FileSpec extraction, job.infiles -> job.indata
> Pilot info: FileSpec implementation

- pilot/info/basedata.py
- pilot/info/jobdata.py
- pilot/info/jobinfo.py
Infosys upgrade:
- implemented Job params validation logic to extract/remove custom options 
- added  `--overwriteQueueData` option to customize `QueueData` settings coming from job params, `jobinfo` fixed to consider `job.overwrite_queuedata`
- extract ZIP_MAP values from Job Params and store them in job object (`JobData.zipmap`)
An example of overwrite Queue data format:
`--overwriteQueueData "{'allowfax':False, 'param':20}"`
> Infosys: manage custom options from JobParams (--overwriteQueueData, ZIP_MAP)

- pilot/api/data.py
- pilot/common/errorcodes.py
- pilot/control/data.py
- pilot/copytool/gfal.py
- pilot/copytool/rucio.py
- pilot/info/configinfo.py
- pilot/info/filespec.py
- pilot/info/infoservice.py
- pilot/info/jobdata.py
- pilot/test/test_harvester.py
- pilot/util/default.cfg
re-factoring of Data API (`pilot.api.data`):
- simplified and fixed workflow for Stage clients
- implemented `resolve_replicas()` which fetches replica details from Rucio and populates FileSpec objects
- pilot.api.data updates (invoke resolve_replicas if need -- `require_replicas` )
- implemented (default) resolve_replica function (a copytool can overwrite it and customize allowed schemas)
- allow to run transfers without `infosys` initialization (but requires to explicitly set `inputddms` data for files in order to resolve allowed source for replica lookup)
`pilot.control.data` updates:
- use data API for stage in
- `rucio` mover upgrade (use filespec as input for stage-in)
- `gfal` copytool: reimplemented stage-in operation using FileSpecs as input
- fix stage-out logic (bug fix) …
> Data API updates, stage-in contol (Movers resolve replicas)

- pilot/copytool/xrdcp.py
- pilot/info/jobdata.py
- pilot/info/queuedata.py
- pilot/user/atlas/common.py
- rucio mover upgraded (consider FileSpecs for stage-out, quick implementation of checksum verification for stage-out, report back pfn/turl value)
- clean up: deprecate plain jobdata fields (ddmendpointin, ddmendpointout, scopein, scopeout, scopelog, logfile, outfiles, logguid, datasetout)
- various fixes
> Clean up & rucio mover implementation (stage-out)

- pilot/api/data.py
- pilot/copytool/rucio.py
Data API updates and bug fixes.
**Examples**
1. An example of data API usage without `infosys` initialization
```python
from pilot.api import data
from pilot.info import FileSpec
client = data.StageInClient()
files = [{'scope':'mc16_13TeV', 'lfn': 'EVNT.11320990._003958.pool.root.1', 'workdir': '/ccs/home/doleynik/test/', 'ddmendpoint':'RRC-KI-T1_DATADISK'}]
xfiles = [FileSpec(type='input', **f) for f in files]
r = client.transfer(xfiles)
```
please note that you will get an error if there is no replica found at requested DDMEndpoint. To resolve it you can either specify the list of allowed ddmendendpoints to be used as source for replica (using `inputddms` key) or allow to use any ddmendpoint for input by setting `allowremoteinputs=True`
e.g.
(given replica file does not exists at …
> Data API updates and bug fixes

- pilot/copytool/rucio.py
- fix name clashing with `rucio` import
> fix rucio import error

- pilot.py
- pilot/control/job.py
- pilot/info/__init__.py
- pilot/info/extinfo.py
- pilot/info/infoservice.py
- pilot/info/queuedata.py
- pilot/util/information.py
Various updates and clean up:
- set dynamic sleep time between retries from Panda schedconfig source
-  add `QueueData.resource` field to store `panda_resource` value (for further usage instead of values passed into `pilot.py` command line options)
- deprecate `pilot.util.information.set_location`, the file `pilot.util.information` can be removed now
- explicitly initialize info service instance inside `pilot.py` (avoid redundant wrappers), `pilot.info.set_info` can be retired as well.
In general, (currently being mandatory) input options like '-r' (for PandaResource name), '-s' (for ATLAS Site or PandaSite? name or it's just an alias to PandaResource?) can be retired, and corresponding values can be replaced with values automatically resolved on fly from queuedata like …
> infosys cleanup (retire old queries to AGIS)

- pilot/util/timer.py
- preserve/expose original back trace stack on exception in decorated function
> Timeout decorator update

- pilot/api/data.py
- manually sort replicas by priority value since `Rucio.list_replicas` has a bug in ordering
> Order replicas by priority

- pilot/api/data.py
- pilot/common/errorcodes.py
- pilot/control/data.py
- stage out logic updates: ignore the nucleus destination (use a default destination from the `astorages`).
(port `prepare_destinations` logic from Pilot1)
fast test shown that in general workflow works:  https://bigpanda.cern.ch/job?pandaid=4284138141
to be tested with real job requesting store to the nucleus
> Avoid stage out to nucleus

- pilot/api/data.py
- pilot/info/extinfo.py
- pilot/info/jobdata.py
- pilot/info/jobinfo.py
- pilot/info/queuedata.py
`pilot.infosys` updates:
-  implemented functionality to customize/overwrite `StorageData` settings with values coming from job parameter (using `--overwriteStorageData` option), in particular to overwrite protocol endpoint to be used for stage-out
- support also customization of protocol  types/schemes to be used  for required activity/copytool using new `acopytools_schemas` settings of `QueueData` that can also be overwritten by Job params (using `--overwriteQueueData` option)
`acopytools_schemas`  format:
```
acopytools_schemas = {}  
```
Examples of `overwriteQueueData`  + `overwriteStorageData` options for Job params:
given example enforces to use `gsiftp` protocol for stage-in  (for any copytool configured for given PQ if copytool supports the protocol), `webdav` to store logs and …
> StorageData overwrite (customize and prioritize protocols to be used for transfers at job level)

- pilot/user/atlas/proxy.py
David Cameron noticed that it would have no sense to call "lsetup emi" when ALRB_noGridMW is set
> Not calling lsetup on ALRB_noGridMW=yes

- pilot/util/timer.py
`TimedProcess` bugfix: properly propagate exception in case of function failure
**Note**: current implementation does not preserve original stack trace on exception: to be implemented separately.
> Timeout decorator fix

- pilot/util/timer.py
Thread-based implementation of the timer (`TimedProcess`): expose original traceback in `stderr` on exception.
**Note**: since `traceback` instance can not be pickled in python by default (so that it's kind of a challenge to re-raise exception occurred  in different thread with original traceback instance) I think that exposing traceback details in `stderr` will be appropriate enough solution for checking details inside the log without overcomplicating  implementation and introducing extra dependencies to external package like `python-tblib` that allows to pickle tracebacks.
> Timeout decorator: print original traceback in stderr

- pilot/api/data.py
- pilot/copytool/gfal.py
- pilot/info/jobinfo.py
- fix copytools failover logic for stage-in (enforce replica look up for copytool allowed schemas)
- add `root://` protocol into supported list for the `gfalcopy` sitemover
> Copytools failover fix

- pilot/api/data.py
- pilot/common/errorcodes.py
- pilot/common/exception.py
- pilot/control/data.py
- pilot/copytool/rucio.py
Instead of a traceback, this now reports the real error returned from rucio download or upload. However, the current version of rucio does not propagate errors well so the message will always be "None of the requested files have been downloaded". I'm working on fixing this so a future version of Rucio will report the real error.
> Better error reporting for rucio mover errors

- pilot/copytool/common.py
- pilot/copytool/rucio.py
Obtain error information from information that Rucio adds to the traces in the download and upload clients. This information will only be available when the pilot can use a rucio release in which https://github.com/rucio/rucio/issues/2925 is fixed. Until then the generic "no files could be downloaded" will be shown.
Once that release is available the pilot call to `rucio.uploadclient.upload` can be changed to add `traces_copy_out=trace_report_out` in order to get the traces info.
> Propagate error info from rucio traces

- pilot/copytool/rucio.py
IMPORTANT! Do not merge until the rucio version used by the pilot is 1.20.7 or later, since the arguments added here are not available until that version.
1.20.7 has been in testing for a week and tomorrow I'll discuss with the DDM people whether we can set it as default.
> get traces info back from rucio for better error message

- pilot/api/data.py
- pilot/control/data.py
- use PanDA preference for stage-out destination (data+log files)
- fail job if PanDA does not explicitly say where to store output (if ddmEndPointOut is not filled for whatever reasons, no smart defaults by Pilot anymore)
> Stage out update for analy prod unification 

- pilot/copytool/rucio.py
- pilot/util/timer.py
- pilot/workflow/generic.py
- fix `timer.TimedProcess` logic
- enable timeout protection for transfers using rucio copytool  (`copy_in` & `copy_in` methods)
> Resolve timeout issues

- pilot/copytool/rucio.py
- pilot/util/timer.py
- `timeout` decorator update: allow passing `Timer` class implementation. Fix python3 compatibility issue with `TimedThread` code)
- Switch from Process-based to Thread-based timer implementation for transfer operations by rucio copytool
> Use Thread-based timeout implementation for rucio copytool 

- pilot/info/dataloader.py
- pilot/info/extinfo.py
- pilot/info/infoservice.py
- pilot/util/default.cfg
- pilot/util/https.py
1. Migrate Pilot to use `CRIC` API & CVMFS caches published by `CRIC` instead of `AGIS` source.
2. in addition following updates have been applied:
-  upgrade `pilot.info.DataLoader` to use authenticated SSL access to query information system with pilot's certificate passed
-  make `pilot.info` configurable for a `VO`: allow to specify custom input JSON data from external information sources (isolate locations of queuedata/queues/storages/cvmfs JSONs into the config file)
- update `pilot.utils.https`: add proper `SSL` context initialization in  `https_setup`
**Notes for automatic passing client certificates**:
`pilot.info.DataLoader` uses global ssl context settings `ctx` which is initialized by `https_setup()` from `pilot.utils.https`. So that to get pilot SSL certificate properly being …
> Migration to CRIC

- pilot/info/extinfo.py
Fix issue with missing new (CRIC related) entries in old configuration file used by clients (HPC affected issue)
> pilot.info: ignore missing entries in the Pilot configuration

- pilot/util/https.py
bugfix in `cacert()` function: properly consider `--cacert` option to be used for certificate lookup/verification instead of `--capath`
This fix should affect only pilots run with custom `--capath` and `--cacert` input CLI arguments (HPC?) 
Regular pilots should not be affected since they I believe use `X509_USER_PROXY` environ.
> Cacertbugfix

- pilot/util/auxiliary.py
HTCondor classads may contain multiple attributes matching the pattern, e.g.:
```
GlobalJobId = "cloud-htcondor-ce-1-kit.gridka.de#46794.0#1606743653"
SubmitterGlobalJobId = "aipanda184.cern.ch#7873849.0#1606743625"
```
With the current pattern, this would be resolved to the exceptionally long string:
```
Submitteraipanda184.cern.ch#7873849.0#1606743625 \ncloud-htcondor-ce-1-kit.gridka.de#46794.0#1606743653
```
Worse, since the order of the attributes is not guaranteed, it may also be resolved to:
```
cloud-htcondor-ce-1-kit.gridka.de#46794.0#1606743653\nSubmitteraipanda184.cern.ch#7873849.0#1606743625
```
Due to the ambiguity, we have observed many jobs being killed with:
```
got an update request with invalid batchID=cloud-htcondor-ce-1-kit.gridka.de#42815.0#1606603131Submitteraipanda184 …
```
> Fix batchsystem jobid extraction with HTCondor

- pilot/user/atlas/container.py
- pilot/user/atlas/proxy.py
verify_arcproxy() asks and remember validation_end time from the first
"arcproxy" command execution. Repeated verify_arcproxy() calls make
a decision based on the data stored in the cache without "arcproxy"
command execution.
proxy_id parameter is used to identify verification results of various proxies,
by default proxy_id='pilot'. When proxy_id is None, verify_arcproxy() doesn't
use cache and remember results.
Proxies renewals are not expected and not implemented, but such support can be added
later if necessary.
> new feature:

- pilot/copytool/common.py
The expected rate of 0.5MB/sec is too low and causes excessive timeouts on problems. For the local stage-ins we should be able to expect throughputs of 5MB/sec (which is still too small IMHO, but we can start with that).
> Increase timeout rate from 0.5MB/sec to 5MB/sec

- pilot/copytool/common.py
After some studies of the actual values from the last 3 months, 5 MBps was a bit too hopeful. Reduce to 1MBps, which is still a 50% improvement to the previous.
> Reduce from 5MBps to 1MBps

- pilot/api/data.py
- pilot/copytool/mv.py
- make free space check procedure (`check_availablespace`) being optional for specific copytools;
- ignore the check for `mv` copytool
> Ignore free space check calculation for mv copytool

- pilot/info/extinfo.py
- pilot/util/default.cfg
By default use static JSON caches from CRIC instead of dynamic query for PandaQueues and DDMEndpoints.
unless custom urls are explicitly specified in the pilot config file
updates: few optimization applied to retrieve only corresponding JSON data for required PQ in case of single PQ request by `pilot.info`
> use static JSON caches from CRIC
